#!/bin/bash

############################
#	functions zone	
############################

init_core()
{
	#do the initialization here
	echo "Initialized moob repo in ~/.moob!"
	mkdir ~/.moob
}

init()
{
	if [ -d ~/.moob ]
	then
		echo -n "a moob repo already exists , init anyway ? (y/n) : "
		read choice

		if [ $choice == "y" -o $choice == "Y" ]
		then
			echo -n "bringing down current repository... "
			rm -rf ~/.moob
			echo "DONE"
			init_core
		fi
	else
		init_core
	fi
}

show_all()
{
	for f in ~/.moob/*; do
		lines=$(cat $f | wc -l | tr -d ' ')
		file=$(echo $f | cut -d "/" -f5)
		echo "> " $file " ($lines) "
	done
}

########################################################

if [ $1 == "init" ]
then
	init
elif [ $1 == "all" ]
then
	show_all
fi
